#!/home/rhewett/anaconda3/bin/python3.8
# -*- coding: utf-8 -*-
import re
import sys

from mprof import main
import mprof

# Monkey patch the plotter
from mprof_plotter import plot_file
mprof.plot_file = plot_file

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
